# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geeks in Progress
email: dev@geeksinprogress.com
description: > # this means to ignore newlines until "baseurl:"
  Join us each week for discussions on recent news in gaming, game development and geek culture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://geeksinprogress.github.io" # the base hostname & protocol for your site
twitter_username: geeksnprogress
github_username:  geeksinprogress

# Build settings
markdown: kramdown
