#cannot change
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false

title: Geeks in Progress
description: > # this means to ignore newlines until "baseurl:"
  Join us each week for discussions on recent news in gaming, game development and geek culture.
excerpt: Listen in on the geeks in progress

baseurl: ""

url: "http://geeksinprogress.github.io"

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jemoji

social: 
  email: social@geeksinprogress.com
  twitter: geeksnprogress
  github: geeksinprogress

# Build settings
markdown: kramdown

managingEditor: "chris@geeksinprogress.com (Chris)"
webMaster: "chinn@geeksinprogress.com (Michael Chinn)"

podcastFeedUrl: "http://rss.podcast.geeksinprogress.com"
podcastFileUrl: "http://files.podcast.geeksinprogress.com"

logo: "https://s3.amazonaws.com/geeksinprogress/files/logo.jpg"

itunes:
  name: Michael Chinn
  email: apple@mechinn.com
  explicit: 'yes'
  categories:
    - text: "TV & Film"
    - text: "Games & Hobbies"
      subcategories:
      - text: "Video Games"
      - text: "Hobbies"
